#atomic vector number 
avchr <- c("one","two", "three")
avint <- as.integer(c(1,2,3))
avlog <- c(TRUE,FALSE,TRUE,FALSE)
typeof(avchr)
typeof(avint)
typeof(avlog)
class(avchr)
class(avint)
class(avlog)
matrixdata<-c((1:12)*2)
mat4x3 <- matrix(matrixdata, nrow = 4, ncol=3, byrow=FALSE)
print(mat4x3)
